GET https://192.168.1.22/mgmt/cm/global/appsvcs-templates HTTP/1.1
X-F5-Auth-Token: eyJraWQiOiJmMGM2MWZlNS0yMzhlLTRmYWQtODNjYi0xZTVjMGE1NWZiNTQiLCJhbGciOiJSUzM4NCJ9.eyJpc3MiOiJCSUctSVEiLCJqdGkiOiJWd2Z5UUsxUldYTk4tT3c0WXQ3VjN3Iiwic3ViIjoiYWRtaW4iLCJhdWQiOiIxOTIuMTY4LjEuMjgiLCJpYXQiOjE2MDEzNTA0MDgsImV4cCI6MTYwMTM1MDcwOCwidXNlck5hbWUiOiJhZG1pbiIsImF1dGhQcm92aWRlck5hbWUiOiJsb2NhbCIsInVzZXIiOiJodHRwczovL2xvY2FsaG9zdC9tZ210L3NoYXJlZC9hdXRoei91c2Vycy9hZG1pbiIsInR5cGUiOiJBQ0NFU1MiLCJ0aW1lb3V0IjozMDAsImdyb3VwUmVmZXJlbmNlcyI6W119.AoAKXN66S5vGQVcsh3DlOCLlFdguBfpk5AtNBGLJaZyA_zXZoEwBHEJD8gSlqYMgSOK_pIK9bOmcWKJzvedg0yEBTmL5y6M0xHwOBzetH6LlVMvaTy9tiuRbrudeeoRq3A23JFK0YsxRkDu10JV6r2mUNaGUQviGDXhmVJUCQhIQz6XN-2CfGM1cjW1EFZQlV8X9wbvT1FUA-C-m8nS4UfYOKNsslA3bwAmgZVrTno4BHfQPB7KEgRUV5D9dIWaDaDzexoFdPsWYlqPWgKIPFWoCCtHjPu1ZRnhGZTIweatti30-HR-C4RzpsMDyt7X8C_QiUPSN8-TAhw62JdDiP9XUysAmmq5RTto7GqcwyPvioli1iRTtOEmwugarM5lPXNlheSm_sJBov2qX4oO32Cm8eKlXi_Nu0bLt7NDBkQGKrDdfySKiLQwlvliqFwUnf0cPapUPxcHNsq8OhzEzBizs3ConlSwbpK7gxIsEuqM1JwD4eNo8vPxLvddKTSI-
Content-Type: application/json

